/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uff.ic.gems.tipmerge.gui;

import br.uff.ic.gems.tipmerge.coverage.TreeTable;
import br.uff.ic.gems.tipmerge.model.Coverage;
import br.uff.ic.gems.tipmerge.model.EditedFile;
import br.uff.ic.gems.tipmerge.model.IconManager;
import br.uff.ic.gems.tipmerge.model.Medalist;
import br.uff.ic.gems.tipmerge.model.MergeCommits;
import br.uff.ic.gems.tipmerge.model.MergeFiles;
import br.uff.ic.gems.tipmerge.model.RankingGenerator;
import br.uff.ic.gems.tipmerge.model.Repository;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Vector;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.LayeredBarRenderer;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author j2cf
 */
public class JFrameRankingCoverageFile extends javax.swing.JFrame {

    final private JTable jTableRanking = new JTable();
//    final private String databaseName = "data/gitdataminer.sqlite";
//    private Repository repository;
    private RankingGenerator rGenerator;

    public Set<EditedFile> filesOfInterest = new HashSet<>();
    private List<Coverage> coverageList1;
//    private List<Coverage> historycoverageList;
    private Map<String, Integer[]> fileNames1;
//    private Map<String, Integer[]> historyfileNames;
//    private MergeCommits merge;

    public JFrameRankingCoverageFile(Repository repository) {
        initComponents();
        initVariables(repository);
    }

    public JFrameRankingCoverageFile(Repository repository, MergeFiles mergeFiles, Map<EditedFile, Set<EditedFile>> dependenciesBranchOne, Map<EditedFile, Set<EditedFile>> dependenciesBranchTwo) {
        initComponents();
        //this.repository = repository;
        initVariables(repository);
        mergesList.setModel(new JComboBox(new String[]{mergeFiles.getHash()}).getModel());

        //merge = new MergeCommits(mergeFiles.getParents()[0], mergeFiles.getParents()[1], repository.getProject());

//	if(dependenciesBranchOne.size() > 0)
        for (EditedFile file : dependenciesBranchOne.keySet()) {
            this.filesOfInterest.add(file);
            this.filesOfInterest.addAll(dependenciesBranchOne.get(file));
        }
//      if(dependenciesBranchTwo.size() > 0)
        for (EditedFile file : dependenciesBranchTwo.keySet()) {
            this.filesOfInterest.add(file);
            this.filesOfInterest.addAll(dependenciesBranchTwo.get(file));
        }
        this.filesOfInterest.addAll(mergeFiles.getFilesOnBothBranch());

        rGenerator = new RankingGenerator();
        Set<EditedFile> excepiontFiles = rGenerator.setMedalsFilesEditedBothBranches(mergeFiles);
        excepiontFiles = rGenerator.setMedalFromDependenciesBranch1(dependenciesBranchOne, mergeFiles, excepiontFiles);
        excepiontFiles = rGenerator.setMedalFromDependenciesBranch2(dependenciesBranchTwo, mergeFiles, excepiontFiles);
        excepiontFiles.removeAll(excepiontFiles);
        //List<Medalist> ranking = rGenerator.getRanking();
        //showRanking(ranking);
        showCoverage(rGenerator);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txProjectName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        mergesList = new javax.swing.JComboBox();
        labelLoading = new javax.swing.JLabel();
        jPanelCover = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Developers Recommendation");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setText("Repository Name");

        txProjectName.setEnabled(false);

        jLabel14.setText("Branches / Merge");

        mergesList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mergesListActionPerformed(evt);
            }
        });

        labelLoading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/uff/ic/gems/tipmerge/icons/loading1.gif"))); // NOI18N
        labelLoading.setText("Loading ...");
        labelLoading.setVisible(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(labelLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mergesList, 0, 550, Short.MAX_VALUE)
                            .addComponent(txProjectName))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(mergesList, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelLoading)
                .addContainerGap())
        );

        jPanelCover.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelCoverLayout = new javax.swing.GroupLayout(jPanelCover);
        jPanelCover.setLayout(jPanelCoverLayout);
        jPanelCoverLayout.setHorizontalGroup(
            jPanelCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelCoverLayout.setVerticalGroup(
            jPanelCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void mergesListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mergesListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mergesListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelCover;
    private javax.swing.JLabel labelLoading;
    private javax.swing.JComboBox mergesList;
    private javax.swing.JTextField txProjectName;
    // End of variables declaration//GEN-END:variables

    private void showRanking(List<Medalist> ranking) {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int column) {
                if (column == 0) //Return the first column as checkbox  
                {
                    return Boolean.class;
                }
                return super.getColumnClass(column);
            }
        };
        Icon mGold = new ImageIcon(getClass().getResource("/br/uff/ic/gems/tipmerge/icons/gold1.png"));
        Icon mSilver = new ImageIcon(getClass().getResource("/br/uff/ic/gems/tipmerge/icons/silver1.png"));
        Icon mBronze = new ImageIcon(getClass().getResource("/br/uff/ic/gems/tipmerge/icons/bronze1.png"));
        JLabel lblGold = new JLabel("Gold");
        JLabel lblSilver = new JLabel("Silver");
        JLabel lblBronze = new JLabel("Bronze");
        lblGold.setIcon(mGold);
        lblSilver.setIcon(mSilver);
        lblBronze.setIcon(mBronze);
        String[] columnLabels = {"Select", "Ranking", "Committer", "Gold", "Silver", "Bronze", "Total"};
        model.setColumnIdentifiers(columnLabels);
        int rank = 1;
        for (Medalist m : ranking) {
            int gold = m.getGoldMedals();
            int silver = m.getSilverMedals();
            int bronze = m.getBronzeMedals();
            int total = gold + silver + bronze;
            String name = m.getCommitter().getName();
            model.addRow(new Object[]{Boolean.FALSE, rank++ + "º", name, gold, silver, bronze, total});
        }
        jTableRanking.setModel(model);
        JCheckBox boxer = new JCheckBox();
        JTableRenderer jTableRender = new JTableRenderer();
        jTableRanking.getColumnModel().getColumn(3).setHeaderValue(lblGold);
        jTableRanking.getColumnModel().getColumn(3).setHeaderRenderer(jTableRender);
        jTableRanking.getColumnModel().getColumn(4).setHeaderValue(lblSilver);
        jTableRanking.getColumnModel().getColumn(4).setHeaderRenderer(jTableRender);
        jTableRanking.getColumnModel().getColumn(5).setHeaderValue(lblBronze);
        jTableRanking.getColumnModel().getColumn(5).setHeaderRenderer(jTableRender);
        jTableRanking.getColumnModel().getColumn(3).setCellRenderer(jTableRender);
        jTableRanking.getColumnModel().getColumn(4).setCellRenderer(jTableRender);
        jTableRanking.getColumnModel().getColumn(5).setCellRenderer(jTableRender);
        //panelRanking.setViewportView(jTableRanking);
    }

    private void initVariables(Repository repository) {
        this.txProjectName.setText(repository.getName());
        mergesList.setModel(new JComboBox(repository.getListOfMerges().toArray()).getModel());
    }

    public void coverageChart(CategoryDataset dados) {
        CategoryAxis categoryAxis = new CategoryAxis("Modified Files");
        ValueAxis valueAxis = new NumberAxis("Number of Methods");
        CategoryPlot plot = new CategoryPlot(dados, categoryAxis, valueAxis, new LayeredBarRenderer());
        plot.setOrientation(PlotOrientation.HORIZONTAL);
        LayeredBarRenderer renderer = (LayeredBarRenderer) plot.getRenderer();
        renderer.setSeriesBarWidth(0, 1.5);
        renderer.setSeriesBarWidth(1, 0.6);
        renderer.setItemMargin(0.02);
        CategoryAxis domainAxis = plot.getDomainAxis();
        domainAxis.setCategoryMargin(0.25);
        domainAxis.setUpperMargin(0.05);
        domainAxis.setLowerMargin(0.05);
        BarRenderer rendered1 = (BarRenderer) plot.getRenderer();
        rendered1.setDrawBarOutline(false);
        GradientPaint gradientpaint1 = new GradientPaint(0.0F, 0.0F, Color.GRAY, 0.0F, 0.0F, new Color(0, 0, 0));
        GradientPaint gradientpaint2 = new GradientPaint(0.0F, 0.0F, Color.GREEN, 0.0F, 0.0F, new Color(0, 64, 0));
        rendered1.setSeriesPaint(0, gradientpaint1);
        rendered1.setSeriesPaint(1, gradientpaint2);
        JFreeChart graphic = new JFreeChart("Coverage Chart", JFreeChart.DEFAULT_TITLE_FONT, plot, true);
        ChartPanel chartPanel = new ChartPanel(graphic);
        chartPanel.setPreferredSize(new java.awt.Dimension(590, 350));
        JFrame chartFrame1 = new JFrame();
        chartFrame1.setContentPane(chartPanel);
        chartFrame1.setBounds(120, 20, 500, 500);
        chartFrame1.setVisible(true);
    }

    private void showCoverage(RankingGenerator ranking) {

        Runnable r;
        r = new Runnable() {

            public void run() {
                labelLoading.setVisible(true);

                TreeTable treeTable = new TreeTable(ranking);

                JScrollPane jpanel = new JScrollPane(treeTable.getTreeTable());

                jpanel.setPreferredSize(jPanelCover.getPreferredSize());
                jPanelCover.removeAll();
                jPanelCover.setLayout(new BorderLayout());
                jPanelCover.add(jpanel);
                jPanelCover.updateUI();

                labelLoading.setVisible(false);
            }

        };
        Thread t = new Thread(r);
        t.start();

    }

}
